//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp931.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Types
    {
        public Types()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int TypeID { get; set; }
        public string NameType { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
